/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData document = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electrical = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData floor = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kitchen = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData multiHome = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pipe = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeVal = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addToCalendar = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backTopAppBar = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendarEvent16 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendarEvent24 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chatWithCommunity = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chatCircleDots = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkCircle = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_16 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discover = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_24 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globeLocation = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData liveSession = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationRing = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pdf = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData selected = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData selected1 = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData selected2 = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData selected3 = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData selected4 = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData selected5 = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stroke = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stroke1 = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stroke2 = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stroke3 = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stroke4 = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stroke5 = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telegram = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userCheckFollowing = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usersGroup = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watchVideo = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
